### ISSUE TITLE
Unable to show stack trace, mkstemp failed 3

### ISSUE THREAD

**Issue by Phyks** [shlomimatichin/Voodoo-Mock#17]
I am not sure whether this should occur or not, but here is what I got when modifying the first available example (not passing, but this is expected).

```
Running all tests
Running 1 fresh suites (total 1)
.
Suite 'build_unittest/tests_Test_Map.bin' failed:

COUNT 2

SUITE 'Test'

TEST 'test_Read'
1

In Test::test_Read:
../../voodoo/VoodooCommon/Scenario.h:277: Error: Test failed: Scenario DEFAULT expected 5 events, but only 4 happened. Next waiting: '
./tests/Test_Map.h:29: Expected Call to bidule2, but found nothing happened'
build_unittest/tests_Test_Map.bin[0x414ad5]
build_unittest/tests_Test_Map.bin[0x41cb89]
build_unittest/tests_Test_Map.bin[0x409622]
build_unittest/tests_Test_Map.bin[0x404f38]
build_unittest/tests_Test_Map.bin[0x40cbf8]
build_unittest/tests_Test_Map.bin[0x40c91c]
build_unittest/tests_Test_Map.bin[0x40c596]
build_unittest/tests_Test_Map.bin[0x40c1fb]
build_unittest/tests_Test_Map.bin[0x40d12c]
build_unittest/tests_Test_Map.bin[0x409a02]
/lib/x86_64-linux-gnu/libc.so.6(__libc_start_main+0xf5)[0x2aaf6b7c2ec5]
build_unittest/tests_Test_Map.bin[0x402559]
Unable to show stack trace, mkstemp failed 3

TEST 'test_Write'

FAILED!
```

I am using a fresh git clone and just modifying the example1, with some error in the scenario. What worries me is the `Unable to show stack trace, mkstemp failed 3` line.

**Comment by shlomimatichin** [comment]
Hello Lucas,
The file voodoo-mock/cxxtest/cxxtest/PrintStack.h ( https://github.com/shlomimatichin/Voodoo-Mock/blob/master/cxxtest/cxxtest/PrintStack.h line 93 ) calls mkstemp, and the errno returned is 3... This is strange, ESRCH==3 is not an errno documented in "man mkstemp". Any idea why that would happen? are you using Windows / Linux? Could you try and write a small test-tool for mkstemp to check if it's working on your platform outside of the test environment?

btw, the first error says that your code-under-test did not call "bidule2", but i guess you already knew that.

good luck!
Shlomi.

**Comment by Phyks** [comment]
Hello,

I will try to debug mkstemp more in depth and come back with some feedback, I agree this error is kind of weird. I am using a standard Ubuntu 14.04 and standard g++ compiler for this test.

And yes, I knew about the `bidule2` error, that was kind of intentional :)

**Comment by Phyks** [comment]
@shlomimatichin I think I found the problem, from `man mkstemp`:
```
RETURN VALUE
       On success, these functions return the file descriptor of the temporary file.  On error, -1 is returned, and errno is set appropriately.
```

Then, test on line 93 and following should be, if I did not miss anything,
```
if (result == -1) {
    printf( "Unable to show stack trace, mkstemp failed %d\n", errno );
    return;
}
```

**Comment by shlomimatichin** [comment]
Nice catch, thank you, and appologies...
try the newly pushed branch "lucas", if the patch works, i'll push it to master too.
let me know,
and thanks again,
Shlomi.

**Comment by Phyks** [comment]
I can confirm the fix, thank you very much for the quick fix!

**Comment by shlomimatichin** [comment]
ok, great. case closed. thanks.
